[package]
name = "daily-retro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "*", default-features = false, features = ["sqlite"] }
dotenvy = "0.15"
